version: '3'
services:
  node:
    build: .
    image: conservativ/nodejs2022q4-service-api
    depends_on:
      - postgres
    command: npm run nodemon
    restart: always

    ports:
      - ${PORT}:${PORT}
    environment:
      - ${PORT}
    volumes:
      - ./src:/usr/app/src

  postgres:
    restart: always
    build: ./database/
    image: conservativ/nodejs2022q4-service-postgres

    # create volumes it save our data
    volumes:
      - nodejs-service:/data/db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

# our data will be available outside
volumes:
  nodejs-service:
