version: '3'
services:
  node:
    build: .
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    environment:
      - ${PORT}
  postgres:
    restart: always
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
